### ISSUE TITLE
K40 Whisperer won't run on my Mac after I've updated it to Big Sur

### ISSUE THREAD

**Issue by orlandoalexander** [rsre/K40-Whisperer-macOS#14]
Hi,

I sent you an email, but I thought I may as well post the issue here too. I saw that someone else had an identical issue, so I downloaded the package you created to solve their issue, but the same error still occurs for me. I was wondering if you could help?

Thanks so much,
Orlando

**Comment by rsre** [comment]
Hi Orlando,

I did not receive your email. Can you please tell me which version of macOS are you running and describe the problem? You might get more information by right clicking the app, "Show Package Content" and then directly executing the file inside the MacOS directory.

I have released a few packaged versions since that issue and they all seem to run fine on macOS Big Sur 11.1 with the latest updates (v0.55 and v0.56). You might want to try those as well.

<img width="912" alt="Screenshot 2021-01-29 at 13 25 56" src="https://user-images.githubusercontent.com/12608029/106329434-b3b1a880-6281-11eb-9bd4-dc36b4634f4e.png">


R

**Comment by orlandoalexander** [comment]
Hi,

Thanks for your reply. I feel a bit silly now, but I have always been running it directly from terminal using the source code directory and didn't think to download the dmg file! Anyways, it works now! Thanks for your help.

**Comment by rsre** [comment]
I'm happy it works now.

Have fun :)
